#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$AIRFLOW_USER" --dbname "$AIRFLOW_DB" <<-EOSQL
    CREATE USER $MAIN_USER WITH PASSWORD '$MAIN_PASSWORD';
    CREATE DATABASE $MAIN_DB;
    GRANT ALL PRIVILEGES ON DATABASE $MAIN_DB TO $MAIN_USER;
EOSQL
